services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newssearch-app
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
#      - db
      - redis

#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: secret
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.1-alpine
    container_name: newssearch-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: