services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newssearch-app
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - redis

  redis:
    image: redis:8.2.1-alpine
    container_name: newssearch-cache
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data: