apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\avina\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Sun, 21 Sep 2025 08:12:16 IST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: cluster_info
    server: https://127.0.0.1:55121
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 21 Sep 2025 08:12:16 IST
        provider: minikube.sigs.k8s.io
        version: v1.37.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\avina\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\avina\.minikube\profiles\minikube\client.key