apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newssearch-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newssearch-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newssearch-cache
  template:
    metadata:
      labels:
        app: newssearch-cache
    spec:
      containers:
        - name: newssearch-cache
          image: redis:8.2.1-alpine
          command: [ "redis-server","--appendonly","yes" ]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: newssearch-cache
spec:
  type: ClusterIP
  selector:
    app: newssearch-cache
  ports:
    - port: 6379
      targetPort: 6379