apiVersion: apps/v1
kind: Deployment
metadata:
  name: newssearch-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newssearch-ui
  template:
    metadata:
      labels:
        app: newssearch-ui
    spec:
      containers:
        - name: newssearch-ui
          image: haridasuavinash/newssearch-ui
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: newssearch-app
spec:
  type: NodePort
  selector:
    app: newssearch
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 8081